In [11]:
import numpy as np
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

**For mean absolute error**

In [12]:
def mae(y_predicted, y_true):
    total_error = 0
    n = len(y_true)
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp-yt)
    mae = total_error/n
    return f"Mean absolute error is : {mae} and Total error is : {total_error}"

In [13]:
mae(y_predicted, y_true)

'Mean absolute error is : 0.5 and Total error is : 2.5'

**Now performing this with the numpy**

In [14]:
np.abs(y_predicted - y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [15]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [16]:
def mae(y_predicted, y_true):
    total_error = np.sum(np.abs(y_predicted - y_true))
    mae = np.mean(np.abs(y_predicted - y_true))
    return f"Total error is {total_error} and mean_absolute_error is {mae}"

In [17]:
mae(y_predicted, y_true)

'Total error is 2.5 and mean_absolute_error is 0.5'

**For the binary_cross_entropy function**

In [19]:
np.log([0])

C:\Users\mohni\AppData\Local\Temp\ipykernel_16016\262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [20]:
epsilon = 1e-15

In [21]:
np.log(epsilon)

np.float64(-34.538776394910684)

In [22]:
y_predicted

array([1, 1, 0, 0, 1])

In [23]:
y_predicted_new = [max(i, epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [24]:
1-epsilon

0.999999999999999

In [25]:
y_predicted_new = [min(i, 1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [26]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [31]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [32]:
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)

**Mean squared error**

In [33]:
import math
def mse(y_predicted, y_true):
    total_error = 0
    n = len(y_true)
    for yp, yt in zip(y_predicted, y_true):
        total_error += math.pow((yp-yt), 2)
    mse = total_error/n
    return f"Total error is {total_error} and mean_squared_error is {mse}"

In [34]:
mse(y_predicted, y_true)

'Total error is 1.83 and mean_squared_error is 0.366'

**Now using the numpy**

In [39]:
def mse(y_predicted, y_true):
    total_error = np.sum(np.square(y_predicted-y_true))
    mse = np.mean(np.square(y_predicted-y_true))
    return f"Total error is {total_error} and mean_squared_error is {mse}"

In [40]:
mse(y_predicted, y_true)

'Total error is 1.83 and mean_squared_error is 0.366'