In [1]:
import numpy as np
revenue = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]])

In [2]:
revenue

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

**This is the revenue in us dollars now to converting this in the indian rupees**
**By taking 1 usd = 97 inr**

In [4]:
rupee = revenue*97
rupee

array([[19400, 21340, 24250],
       [ 6596,  7663, 10185],
       [10670, 13580, 17460],
       [ 7760,  8245,  8730]])

**Now to find out the total sales in the flower shop**

In [5]:
units = np.array([[50, 60, 25], [10, 13, 5], [40, 70, 52]])
price_per_unit = np.array([[20, 30, 15]])

In [7]:
total_sales_per_month = price_per_unit.dot(units)
total_sales_per_month

array([[1900, 2640, 1430]])